### ISSUE TITLE
f125 mode 8 decoding broken

### ISSUE THREAD

**Issue by mikestaib** [JeffersonLab/sim-recon#153]
Leaving this here so that it is just marked as a known issue. For now the DigiHit and Hit objects are not being created for the FDC and CDC for mode 8 data so there is no tracking information. The problem comes from here:

``` c++
void JEventSource_EVIO::EmulateDf125PulseIntegral(vector<JObject*> &wrd_objs, vector<JObject*> &pi_objs,
                          vector<JObject*> &pt_objs)
{
    if(VERBOSE>3) evioout << " EmulateDf125PulseIntegral has been disabled" <<endl;
    return;

    // total cop-out by Naomi who cannot see how to make this not crash (even before the code was modified)
```

This bit of code needs reworked to bring things back to a working state.

**Comment by faustus123** [comment]
Naomi was looking into this today. We can expect a fix sometime soon.

**Comment by sdobbs** [comment]
Do we know when this was introduced?

**Comment by faustus123** [comment]
commit 88308efe0c886b6c0d4dfef3fa864bfa41395728
Author: nsjarvis nsj@cmu.edu
Date:   Wed Nov 4 19:04:01 2015 -0500

```
updated fa125 emulator (disabled PI emulation) and added decoder for new fa125 data type 5 CDC pulse data
```

**Comment by nsjarvis** [comment]
Yes, that was it.   I didn’t expect the code to escape from the branch that I put it in, that was supposed to be temporary.   

Naomi.
