### ISSUE TITLE
Dip in Start Counter matching efficiency

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/sim-recon#192]
In the Spring 2015 data, there is a dip in the Start Counter matching efficiency around paddle 22 that has been around for awhile. 

See, e.g., [https://halldweb.jlab.org/cgi-bin/data_monitoring/monitoring/runBrowser.py?run_number=2931&ver=ver24&period=RunPeriod-2015-03](url)
![run2931_ver24_histmacro_matching_sc](https://cloud.githubusercontent.com/assets/1182058/12762869/f5a237b4-c9b6-11e5-8139-c16ca9e2f965.png)

In reference to his studies of Start Counter hit efficiencies, Mahmoud mentioned "I have the same dip in the SS. In the NS i have a dip but for different sectors":

![st_eff_sections](https://cloud.githubusercontent.com/assets/1182058/12762868/f59de07e-c9b6-11e5-89c4-5c83acf11856.png)

**Comment by KMahmoud** [comment]
In the Last Collaboration Meeting I presented why the efficiency has this shape in the Nose Section. When dividing the nose section to 4 equal intervals we get the same efficiency shape in the last 4cm. See slide 18:
http://argus.phys.uregina.ca/gluex/DocDB/0028/002856/001/ST_Efficiency_update.pdf

**Comment by sdobbs** [comment]
Thanks for the reminder.  From your slides it looks like (roughly) for tracks with theta < 10 degrees, the efficiency varies ~+- 30 %.  I'm still not sure why there would be a dip in the straight section, though, since your slides don't show such an effect.

It will be helpful to know if this is an alignment/geometry issue, or one due to thresholds or some other setting of the electronics.

**Comment by sdobbs** [comment]
This issue was discussed in the Feb. 10 Calibration meeting, and it is thought that this problem might be due to overly strict matching criteria in the tip of the nose region where the paddles are small.  @KMahmoud will look at if the hits are in paddles near the expected one.

**Comment by sdobbs** [comment]
Recent efficiency studies have yielded more uniform efficiencies, except in the very tip of the nose, where the geometry is poorly understood.
