### ISSUE TITLE
Problems with electron reconstruction?

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/sim-recon#194]
Cristiano (from MIT) is studying eta -> gamma e+ e- decay in simulations, and found that the mass he was obtaining was ~30 MeV too low.  
![cristiano_etaprime](https://cloud.githubusercontent.com/assets/1182058/12764697/e828a3de-c9c0-11e5-8d2d-878a7b4ae321.png)

The vertex and photon recon/truth comparisons look fine, so it is probable that the problem is with the electron track reconstruction.  There is noticeable energy loss for the reconstructed electrons (see page 5 of 
[eeg_4sean_Jan25.pdf](https://github.com/JeffersonLab/sim-recon/files/114711/eeg_4sean_Jan25.pdf)
). 

@staylorjlab is working on implementing an energy loss calculation for electrons in the Kalman filter, since the current calculation is only correct for pi/K/p.

**Comment by sdobbs** [comment]
The electron reconstruction improvements have been checked in.  Preliminary results from Cristiano look promising, waiting on a larger sample of simulated data to close this.

**Comment by pmattjlab** [comment]
When this gets fixed, we should consider enabling e+/- reconstruction: In the monitoring / reconstruction jobs, and perhaps even by default.

**Comment by curtisameyer** [comment]
I think that WIll McGinley also showed plots of this last week.

## Curtis

Curtis A. Meyer         MCS Associate Dean for Faculty and Graduate Affairs
Wean:    (412) 268-2745 Professor of Physics
Doherty: (412) 268-3090 Carnegie Mellon University
Fax:         (412) 681-0648 Pittsburgh, PA 15213
curtis.meyer@cmu.edu    http://www.curtismeyer.com/

**Comment by wmcginle** [comment]
I briefly looked at this using Spring 2016 data and the pi0 and eta masses were within a few MeV of their expected values, details can be seen in the log entry: https://logbooks.jlab.org/entry/3390076

**Comment by sdobbs** [comment]
Between Will's results from data and Cristiano's from simulation, I think we can close this.

Between the interest in electron for calibration and physics analysis purposes, I do think that we should enable electron reconstruction by default.
