### ISSUE TITLE
Run number from file name? #227 and #234 

### ISSUE THREAD

**Issue by jrstevenjlab** [JeffersonLab/sim-recon#245]
I'm seeing this warning about getting the run number from the evio file name:

JANA >>WARNING: setting run number 10390 based on file name

Is this still expected?

**Comment by sdobbs** [comment]
Could you please post the command line you're running to get this error?

**Comment by jrstevenjlab** [comment]
hd_root -PPLUGINS=p2pi_hists /cache/mss/halld/RunPeriod-2016-02/rawdata/Run010390/hd_rawdata_010390_000.evio

**Comment by sdobbs** [comment]
It looks like the required data is in the file, but the DAQ library hasn't been updated to use it yet, so the short answer is "yes".

**Comment by jrstevenjlab** [comment]
Ok, thanks.  So we'll leave the issue open until this is remedied in the DAQ library.

**Comment by faustus123** [comment]
OK, So I just submitted a pull request #251 that should address this. It seemed to work
for me using hd_rawdata_010390_003.evio renamed to “file.evio”. Let me know if anyone
sees a case where the run_number is not being correctly set after this has been merged. 

Being an optimist, I'm going to go ahead and close this issue.

**Comment by mikestaib** [comment]
The Run number appears to be properly set, but I'm still getting a warning message? 
Running over /gluonraid2/rawdata/volatile/RunPeriod-2016-02/rawdata/Run010391/hd_rawdata_010391_000.evio

JANA >>WARNING: setting run number 10391 based on file name

**Comment by sdobbs** [comment]
This should (finally) be fixed by #290
