### ISSUE TITLE
Effect of NPEAKS=3 in TOF

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/sim-recon#291]
It would be helpful to study to the effect of NPEAKS=3 in the spring 2016 data to see if any changes to the reconstruction code are needed.

**Comment by markdalton** [comment]
Hi Sean,

Can you be more specific on what study you would like to see?

Best,
Mark Macrae Dalton

**Comment by sdobbs** [comment]
It depends on the detector.  For the SC and TOF, they are already filling hits where there is a TDC hit without an associated ADC hit, and the TDCs are already multihit.  So for them it would be mostly sanity checks - making sure the TDC and ADC hits are correctly matched, that the hit distributions are unchanged, etc.  Perhaps the addition of more ADC information could help in determining if a hit is "real" or some sort of reflection.

For the BCAL, leaving aside the issue of the TDCs, you'll at least want to know the rate of having these extra hits, and study how often they are picked up by the cluster/shower reconstruction, and if these hits are real or not (e.g. do they improve the energy/time resolution or not).

**Comment by sdobbs** [comment]
No problems seen, closing...
