### ISSUE TITLE
Possible start counter hole?

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/sim-recon#594]
From Mahmoud:

I run over 250K events of run 11366 using my calibration script . The time resolution for the start counter is ~271 ps, but when you look at the corrected time vz Z, it seems the paddle is divided to half at the beginning of the bend section. Therefore I submitted farm jobs to run over larger amount of data and I started to get the results. From only one file of each run I'm attaching the corrected time vs Z for paddle number 2 as an example. Other paddles have the same feature (more or less).  Is this a geometry issue or a tracking issue?

My sim-recon last updated Oct 7th after all the tracking issues had been fixed.

Example plot:
![Run11555, file1](https://cloud.githubusercontent.com/assets/1182058/19453656/c935ed20-947b-11e6-8493-4f87b42ca5a0.png)

**Comment by pmattjlab** [comment]
SC Matching from ver07 monitoring for run 11366 (file 0): 
![sc_matching](https://cloud.githubusercontent.com/assets/13242148/19454240/5c721262-9486-11e6-98e7-16e74c363422.png)

There doesn't appear to be a problem, although it's vs. theta instead of z, so maybe it washes out (since theta averages over vertex-z)

**Comment by KMahmoud** [comment]
These plots are the z coordinate of the intersection point of the track with the start counter (Directly from the matching,file 000 of run 11366.) for sector 1 & 2. All of the other paddle have the same pattern
![sector1_z](https://cloud.githubusercontent.com/assets/13262753/19519640/c5e8ae04-95da-11e6-83f1-2d51e5ec8bd9.png)
![sector2_z](https://cloud.githubusercontent.com/assets/13262753/19519641/c5ee6416-95da-11e6-884e-eb7e59549095.png)

**Comment by sdobbs** [comment]
It would be useful to verify if this dip corresponds to the bend/straight section boundary.

**Comment by KMahmoud** [comment]
This is the bend/straight boundary. The SC begins at 37cm and the length of the straight section is 40 cm

**Comment by pmattjlab** [comment]
Do you know how long this has been happening?  Is this hole present in the ver01 reconstruction data?  Or was it present prior when you did the original calibrations?

**Comment by KMahmoud** [comment]
It was not present when I did the original calibrations (May/June). I started to see it recently when I started to test if I'm getting the same results with ROOT6.

**Comment by curtisameyer** [comment]
Is it easy to look for in the version 1 production?

## Curtis

Curtis A. Meyer         MCS Associate Dean for Faculty and Graduate Affairs
Wean:    (412) 268-2745 Professor of Physics
Doherty: (412) 268-3090 Carnegie Mellon University
Fax:         (412) 681-0648 Pittsburgh, PA 15213
curtis.meyer@cmu.edu    http://www.curtismeyer.com/

**Comment by pmattjlab** [comment]
This particular quantity (track intersection with SC) is not available on the webpages.  It was not histogrammed for the ver01 reconstruction launch (we didn't run all 30+ monitoring plugins).  Perhaps the SC-specific monitoring plugin fills it?  If it does, the previous launch with this plugin would have been monitoring launch ver05.  Mahmoud, are you guys histogramming this?

**Comment by sdobbs** [comment]
The SC-specific plugins (e.g. st_Tresolution) should be run on the monitoring launches, at least I see the histograms in the ROOT files.  For the recon launches, this effect should be visible in Mahmoud's efficiency studies...

**Comment by KMahmoud** [comment]
In the ST_online_tracking under the monitoring, there is a histogram that plot R vs Z. I will run it and see how it looks like.

**Comment by KMahmoud** [comment]
![st_online_tracking](https://cloud.githubusercontent.com/assets/13262753/19524846/1546ac8c-95ed-11e6-9251-37b5b7e73a13.png)
25K events of file000, run 11366

**Comment by pmattjlab** [comment]
Mahmoud, can you confirm that you're using the latest sim-recon and hdds?  

Also, can you plot this by counter?  That way you can help Simon track things down.

**Comment by KMahmoud** [comment]
HDDS_HOME=/group/halld/Software/builds/Linux_CentOS6-x86_64-gcc4.9.2/hdds/hdds-3.6^root6.06.08
JANA_GEOMETRY_URL=xmlfile:///group/halld/Software/builds/Linux_CentOS6-x86_64-gcc4.9.2/hdds/hdds-3.6^root6.06.08/main_HDDS.xml
HALLD_HOME=/lustre/expphy/work/halld/home/mkamel/SIM_RECON/MASTER_Sim-recon/sim-recon

Last update Oct7th.

**Comment by mikestaib** [comment]
Here is what I see with a newer version of the code for 10k events. Seems it is still kicking around. This is the current master of hdds, and a day or two old sim-recon.

<img width="535" alt="screen shot 2016-10-19 at 11 36 41 am" src="https://cloud.githubusercontent.com/assets/13318376/19525890/7ce247ea-95f0-11e6-9dcd-d749b08c6a2b.png">

**Comment by pmattjlab** [comment]
I get the exact same result.

**Comment by KMahmoud** [comment]
![r_z_sector1](https://cloud.githubusercontent.com/assets/13262753/19528722/20c3fd7c-95fb-11e6-8d11-58b8d3791f69.png)
![r_z_sector2](https://cloud.githubusercontent.com/assets/13262753/19528723/20cfe600-95fb-11e6-9265-078b285661e8.png)

R Vs Z for sector 1 &2 as an example

**Comment by staylorjlab** [comment]
I have made a fix to the st matching code-- once someone has merged the pull request, Mahmoud can you rerun your plugin?

**Comment by sdobbs** [comment]
It is merged...

**Comment by mikestaib** [comment]
Looks to be fixed. Thanks Simon!

<img width="532" alt="screen shot 2016-10-19 at 5 38 45 pm" src="https://cloud.githubusercontent.com/assets/13318376/19538647/0e81f358-9623-11e6-9933-48291e6e75c2.png">

**Comment by KMahmoud** [comment]
![sector1](https://cloud.githubusercontent.com/assets/13262753/19538887/47b567a8-9624-11e6-907a-f235b0237f03.png)
![tracks](https://cloud.githubusercontent.com/assets/13262753/19538888/47bad1c0-9624-11e6-90b7-187b42582e8e.png)
Yes it is fixed, Thanks Simon
