### ISSUE TITLE
segfault running hdgeant

### ISSUE THREAD

**Issue by T-Britton** [JeffersonLab/sim-recon#682]
I am attempting to validate some changes I made to the geometry by using a particle gun.  After commenting out all my detector changes and trying to run the attached control.in (I had to rename it for github to accept the attachment) I get the following segfault:

===========================================================
There was a crash.
This is the entire stack trace of all threads:
===========================================================
#0  0x0000003624aac65d in waitpid () from /lib64/libc.so.6
#1  0x0000003624a3e609 in do_system () from /lib64/libc.so.6
#2  0x0000003624a3e940 in system () from /lib64/libc.so.6
#3  0x00007f8635abc30a in TUnixSystem::StackTrace() () at /u/group/halld/Software/builds/Linux_CentOS6-x86_64-gcc4.9.2/root/root-6.06.08/core/unix/src/TUnixSystem.cxx:2096
#4  0x00007f8635abe46c in TUnixSystem::DispatchSignals(ESignals) () at /u/group/halld/Software/builds/Linux_CentOS6-x86_64-gcc4.9.2/root/root-6.06.08/core/unix/src/TUnixSystem.cxx:3562
#5  <signal handler called>
#6  0x0000000001418c7c in close_s_HDDM ()
#7  0x0000000000605155 in closeOutput ()
#8  0x0000000000627165 in hdgeant_ ()
#9  0x00000000005fa3f0 in main ()
===========================================================

at the end of the geant step.  I do get my .hddm out but this prohibits moving on to the smearing step if requested.  I suspect I am simply doing something wrong but thought it worth pointing out the segfault.

Thanks.
[control.txt](https://github.com/JeffersonLab/sim-recon/files/735527/control.txt)

**Comment by rjones30** [comment]
Hello Thomas,

You must have something else broken in your build. I just ran with the most
recent sim-recon master branch build on my system here at UConn with your
control.txt file (renamed to control.in) and it finished without errors.
Questions:

   1. are you aware that you have disabled mcsmear postprocessing in your
   control.txt file?
   2. are you aware that control.txt is not the name of the file that
   hdgeant looks for, it is control.in?

-Richard Jones

**Comment by T-Britton** [comment]
Thomas Britton

> On Jan 27, 2017, at 1:50 PM, Richard Jones <notifications@github.com> wrote:
> 
> Hello Thomas,
> 
> You must have something else broken in your build. I just ran with the most
> recent sim-recon master branch build on my system here at UConn with your
> control.txt file (renamed to control.in) and it finished without errors.
Interesting. Thanks!

> Questions:
> 
> 1. are you aware that you have disabled mcsmear postprocessing in your
> control.txt file?
Yes, I was debugging the segfault so I cut out the step
> 2. are you aware that control.txt is not the name of the file that
> hdgeant looks for, it is control.in?
> 
Yes, but github does not let me attach *.in so I had to resort to relabeling it to .txt to get around that restriction.

**Comment by rjones30** [comment]
I believe that a rebuild from scratch made this crash go away, and nothing more on this issue has been heard since. I am going to close this ticket, but if it becomes an issue again please reopen it.
